blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/nihldev/terraform-aws-keycloak/discussions
    about: Ask questions and discuss with the community
  - name: Terraform Registry
    url: https://registry.terraform.io/modules/nihldev/keycloak/aws
    about: View module documentation on Terraform Registry
